import { useState } from "react"
import styles from '@/styles/Home.module.css'
import Link from "next/link";
import Navbar from "@/components/Navbar";
import Head from "next/head";

export default function Register() {

    const [registerUsername, setRegisterUsername] = useState('');
    const [registerPassword, setRegisterPassword] = useState('');

    return (
        <>
            <Head>
                <title>Blockchain</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar></Navbar>
            <div className="flex flex-col items-center justify-center min-h-screen bg-gray-100">
                <div className="w-full max-w-md">
                    <h1 className="text-2xl font-bold text-gray-800 mb-8">
                        Registrarse
                    </h1>
                    <div className="mb-4">
                        <label htmlFor="email" className="block font-medium mb-2">
                            Nombre
                        </label>
                        <input
                            type="name"
                            id="name"
                            name="name"
                            className="w-full px-4 py-2 rounded-lg border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 focus:ring-opacity-50"
                        />
                    </div>
                    <div className="mb-4">
                        <label htmlFor="email" className="block font-medium mb-2">
                            Correo electrónico
                        </label>
                        <input
                            type="email"
                            id="email"
                            name="email"
                            className="w-full px-4 py-2 rounded-lg border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 focus:ring-opacity-50"
                        />
                    </div>
                    <div className="mb-6">
                        <label htmlFor="password" className="block font-medium mb-2">
                            Contraseña
                        </label>
                        <input
                            type="password"
                            id="password"
                            name="password"
                            className="w-full px-4 py-2 rounded-lg border-gray-300 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 focus:ring-opacity-50"
                        />
                    </div>
                    <button
                        type="submit"
                        className="w-full bg-indigo-500 text-white py-2 rounded-lg hover:bg-indigo-600 transition-colors duration-300"
                    >
                        Registrarse
                    </button>
                    <div className="mt-8">
                        <Link href="/" className="block mt-2 text-gray-500 hover:underline">
                            Volver al inicio
                        </Link>
                    </div>
                </div>
            </div>
        </>
    )
}