import { useState } from "react"
import styles from '@/styles/Home.module.css'
import Link from "next/link";
import Navbar from "@/components/Navbar";
import Head from "next/head";

export default function Register() {

    const [registerUsername, setRegisterUsername] = useState('');
    const [registerPassword, setRegisterPassword] = useState('');

    return (
        <>
            <Head>
                <title>Blockchain</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Navbar></Navbar>
            <h1>Registrarse</h1>
            <input type="text" className="username" placeholder="Username" onChange={e => setRegisterUsername(e.target.value)}></input><br />
            <input type="text" className="password" placeholder="Password" onChange={e => setRegisterPassword(e.target.value)}></input><br />
            <button>Register</button>

            <Link href={"/"}>Volver</Link>
        </>
    )
}